---
- name: configure common aliases
  ansible.builtin.lineinfile:
    path: "{{ filepath }}"
    line: "{{ item }}"
    create: true
    state: present
  loop:
    - "alias clera='clear'"
    - "alias gs='git status'"
    - "alias gl='git branch -l'"
    - "alias gr='git fetch --all && git reset --hard origin/master'"
    - "alias la='ls -lAogh --group-directories-first'"
    - "alias ls='ls --color=auto'"
    - "alias please='sudo $(history -p !-1)'"
  become: true
